const dataImg = [
  {
    id: 3,
    name: "Kafka",
    title: "Acoustic Guitar Studio",
    urlProfile: "/img/profil/kafka.png",
    category: "Music",
    url: "/img/3.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 10,
    name: "Kafka",
    title: "Dance B&W",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/10.jpg",
    alt: "lorem ipsu",
    like: 0,
  },
  {
    id: 1,
    name: "Kafka",
    title: "Retro Acoustic Guitar",
    urlProfile: "/img/profil/kafka.png",
    category: "Nature",
    url: "/img/1.jpg",
    alt: "lorem ipsum",
    like: 0,
  },

  {
    id: 4,
    name: "Kafka",
    title: "White Coat Fashion Style",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/4.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 5,
    name: "Kafka",
    title: "WaterFall Nature",
    urlProfile: "/img/profil/kafka.png",
    category: "Nature",
    url: "/img/5.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 14,
    name: "Kafka",
    title: "Party Dance B&W",
    urlProfile: "/img/profil/kafka.png",
    category: "Music",
    url: "/img/14.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 6,
    name: "Kafka",
    urlProfile: "/img/profil/kafka.png",
    title: "Woman Model",
    category: "Fashion",
    url: "/img/6.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 7,
    name: "Kafka",
    title: "Clothing",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/7.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 8,
    name: "Kafka",
    title: "Coconut Tree",
    urlProfile: "/img/profil/kafka.png",
    category: "Nature",
    url: "/img/8.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 2,
    name: "Kafka",
    title: "Retro Cassete",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/2.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 9,
    name: "Kafka",
    title: "Woman 80's Style",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/9.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 11,
    name: "Kafka",
    title: "Green Savana",
    urlProfile: "/img/profil/kafka.png",
    category: "Nature",
    url: "/img/11.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 12,
    name: "Kafka",
    title: "Retro man with a woman in a bus travel",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/12.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
  {
    id: 13,
    name: "Kafka",
    title: "80's retro woman walking on the road",
    urlProfile: "/img/profil/kafka.png",
    category: "Fashion",
    url: "/img/13.jpg",
    alt: "lorem ipsum",
    like: 0,
  },
];
export default dataImg;
